import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Cv from "./components/Cv";
import AdminPanel from "./components/AdminPanel";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="/dist/output.css" rel="stylesheet"></link> */}
      </Head>
      <main className={styles.main}>
        <Cv />
        <AdminPanel />
      </main>
    </>
  );
}
